const KEY='marlowe.tasks.v1',WORK_START=480,WORK_END=1020,DAY_CAPACITY=540;
const seedTasks=[{id:'seed-stpeters',title:"Contact St Peter's about book-hire covering",priority:1,minutes:25,due:'2026-08-18',bucket:'today',done:false,category:'Customer follow-up'},{id:'seed-peterpal',title:'Contact Peter Pal about the CoverPro',priority:2,minutes:20,due:'2026-08-18',bucket:'today',done:false,category:'CoverPro'},{id:'seed-schoolprep',title:'Prepare school visit materials + choose route',priority:2,minutes:25,due:'2026-08-18',bucket:'today',done:false,category:'School visits'},{id:'seed-schoolvisits',title:'School visits — aim for 4 local schools',priority:2,minutes:180,due:'2026-08-18',bucket:'today',done:false,category:'School visits'},{id:'seed-stripper',title:'CoverPro paper stripper — protected build block',priority:2,minutes:120,due:'2026-08-18',bucket:'today',done:false,category:'CoverPro'}];
let tasks=JSON.parse(localStorage.getItem(KEY)||'[]');if(!tasks.length){tasks=seedTasks.map((t,i)=>({...t,order:i,created:new Date().toISOString()}));localStorage.setItem(KEY,JSON.stringify(tasks));}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]));
function inferCategory(t){if(t.category)return t.category;const s=(t.title||'').toLowerCase();if(s.includes('school'))return'School visits';if(s.includes('coverpro')||s.includes('stripper'))return'CoverPro';if(s.includes('desk')||s.includes('admin'))return'Admin';if(s.includes('contact')||s.includes('follow'))return'Customer follow-up';return'General'}
tasks=tasks.map((t,i)=>({...t,category:inferCategory(t),scheduledDate:t.scheduledDate||'',scheduledTime:t.scheduledTime||'',order:Number.isFinite(Number(t.order))?Number(t.order):i,recurrence:t.recurrence||((t.category==='Daily')?'daily':''),dailyDoneDates:Array.isArray(t.dailyDoneDates)?t.dailyDoneDates:[]}));
function localISO(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function dateFromISO(s){const[y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}function addDaysISO(s,n){const d=dateFromISO(s);d.setDate(d.getDate()+n);return localISO(d)}function nextBusinessDay(s){let d=addDaysISO(s,1);while([0,6].includes(dateFromISO(d).getDay()))d=addDaysISO(d,1);return d}
function businessLabel(s){return dateFromISO(s).toLocaleDateString(undefined,{weekday:'short',day:'numeric',month:'short'})}function fullDateLabel(s){return dateFromISO(s).toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long',year:'numeric'})}function timeLabel(s){if(!s)return'flexible';const[h,m]=s.split(':').map(Number),a=h>=12?'pm':'am',hh=((h+11)%12)+1;return `${hh}:${String(m).padStart(2,'0')} ${a}`}function fmtClock(total){const h=Math.floor(total/60)%24,m=total%60,a=h>=12?'pm':'am',hh=((h+11)%12)+1;return `${hh}:${String(m).padStart(2,'0')} ${a}`}
function startMinutes(t){if(!t.scheduledTime)return null;const[h,m]=t.scheduledTime.split(':').map(Number);return h*60+m}function endMinutes(t){const s=startMinutes(t);return s==null?null:s+Number(t.minutes||0)}
function isDaily(t){return t.recurrence==='daily'||t.category==='Daily'}function isDoneForDate(t,date=localISO()){return isDaily(t)?(t.dailyDoneDates||[]).includes(date):!!t.done}function setDoneForDate(t,date,value){if(!isDaily(t)){t.done=value;return}const set=new Set(t.dailyDoneDates||[]);value?set.add(date):set.delete(date);t.dailyDoneDates=[...set].sort()}
function minutesForDate(s,exclude=''){return tasks.filter(t=>!isDoneForDate(t,s)&&t.scheduledDate===s&&t.id!==exclude).reduce((a,t)=>a+Number(t.minutes||0),0)}function findNextAvailable(start,mins,exclude=''){let d=start;for(let i=0;i<90;i++){if(![0,6].includes(dateFromISO(d).getDay())&&minutesForDate(d,exclude)+mins<=DAY_CAPACITY)return d;d=addDaysISO(d,1)}return''}
function save(){localStorage.setItem(KEY,JSON.stringify(tasks));if(typeof render==='function')render();else if(typeof renderDay==='function')renderDay()}function score(t){let s=t.priority*100;if(t.due){const d=(new Date(t.due+'T23:59:59')-new Date())/86400000;s+=d<0?-400:Math.min(80,d*12)}if(t.bucket==='today'||isDaily(t))s-=120;return s}function niceDue(t,date=localISO()){if(!t.due)return'';return `<span class="${t.due<date&&!isDoneForDate(t,date)?'overdue':''}">due ${esc(t.due)}</span>`}
function manualSort(a,b){return (Number(a.order)||0)-(Number(b.order)||0)||(a.created||'').localeCompare(b.created||'')}
function scheduledSort(a,b){return ((a.scheduledDate||'9999')+(a.scheduledTime||'99:99')).localeCompare((b.scheduledDate||'9999')+(b.scheduledTime||'99:99'))||manualSort(a,b)}
function normalizeOrder(list){list.forEach((t,i)=>t.order=i)}
function reorderWithin(ids,dragId,targetId){const list=ids.map(id=>tasks.find(t=>t.id===id)).filter(Boolean);const from=list.findIndex(t=>t.id===dragId),to=list.findIndex(t=>t.id===targetId);if(from<0||to<0||from===to)return;const[moved]=list.splice(from,1);list.splice(to,0,moved);normalizeOrder(list)}
function todayFinishMap(td,date=localISO()){let cursor=date===localISO()?Math.max(WORK_START,new Date().getHours()*60+new Date().getMinutes()):WORK_START,map={};td.forEach(t=>{if(isDoneForDate(t,date)){map[t.id]=null;return}const fixed=startMinutes(t);if(fixed!=null){map[t.id]=fixed+Number(t.minutes||0);cursor=Math.max(cursor,map[t.id]);}else{cursor+=Number(t.minutes||0);map[t.id]=cursor}});return map}
window.moveTomorrow=id=>{const t=tasks.find(x=>x.id===id);if(!t||isDaily(t))return;const date=nextBusinessDay(localISO()),used=minutesForDate(date,id),need=Number(t.minutes||0);if(used+need>DAY_CAPACITY&&!confirm(`${businessLabel(date)} already has ${used} minutes scheduled. Adding this ${need}-minute task exceeds the normal 8:00 am–5:00 pm capacity. Move it there anyway?`))return;t.scheduledDate=date;t.scheduledTime='';t.bucket='scheduled';t.order=Date.now();t.done=false;save()};
window.scheduleTask=id=>{const t=tasks.find(x=>x.id===id);if(!t||isDaily(t))return;const suggested=t.scheduledDate||nextBusinessDay(localISO());const date=prompt('Schedule date (YYYY-MM-DD):',suggested);if(date===null)return;if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||Number.isNaN(dateFromISO(date).getTime())){alert('Please enter a date as YYYY-MM-DD.');return}const time=prompt('Start time (HH:MM), or leave blank for a flexible task:',t.scheduledTime||'');if(time===null)return;if(time&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(time)){alert('Please enter the time as HH:MM, for example 12:00.');return}const used=minutesForDate(date,id),need=Number(t.minutes||0);if(used+need>DAY_CAPACITY&&!confirm(`${businessLabel(date)} already has ${used} minutes scheduled. Adding this ${need}-minute task exceeds the normal workday. Schedule it there anyway?`))return;t.scheduledDate=date;t.scheduledTime=time;t.bucket='scheduled';t.order=Date.now();t.done=false;save()};
function taskHTML(t,finishMap={},dragGroup='',viewDate=localISO()){const done=isDoneForDate(t,viewDate),f=finishMap[t.id],late=Number.isFinite(f)&&f>WORK_END,finish=Number.isFinite(f)?`<span class="pill ${late?'late':'finish'}">finish ~${fmtClock(f)}</span>`:'',sched=t.scheduledDate?`<span class="pill scheduled">${businessLabel(t.scheduledDate)} · ${timeLabel(t.scheduledTime)}</span>`:'',daily=isDaily(t)?'<span class="pill daily">Daily</span>':'',res=late&&t.bucket==='today'&&!t.scheduledDate&&!isDaily(t)&&!done?`<button class="warnbtn" onclick="moveTomorrow('${t.id}')">Move to tomorrow</button>`:'',drag=dragGroup?` draggable="true" data-id="${t.id}" data-drag-group="${dragGroup}"`:'';let actionButtons='';if(!isDaily(t)){if(t.scheduledDate){actionButtons=`<button class="ghost" onclick="move('${t.id}')">Unschedule</button>`}else{actionButtons=`<button class="ghost" onclick="move('${t.id}')">${t.bucket==='today'?'Backlog':'Today'}</button><button class="ghost" onclick="moveTomorrow('${t.id}')">Tomorrow</button><button class="ghost" onclick="scheduleTask('${t.id}')">Schedule</button>`}}return `<div class="task ${done?'done':''}${dragGroup?' draggable-task':''}"${drag}><div class="drag-handle" title="Drag to reorder" aria-label="Drag to reorder">⋮⋮</div><input type="checkbox" ${done?'checked':''} onchange="toggleForDate('${t.id}','${viewDate}')"><div><div class="task-title">${esc(t.title)}</div><div class="task-meta"><span class="pill cat">${esc(t.category)}</span>${daily}<span class="pill">${t.minutes} min</span>${sched}${finish}<span class="pill">${['','Urgent','Important','Normal'][t.priority]}</span> ${niceDue(t,viewDate)}</div>${res}</div><div>${actionButtons}<button class="ghost danger" onclick="del('${t.id}')">×</button></div></div>`}
function renderUpcoming(list){if(!list.length)return'<div class="empty">Nothing scheduled.</div>';let last='';return list.map(t=>{const h=t.scheduledDate!==last?`<div class="upcoming-day">${businessLabel(t.scheduledDate)}</div>`:'';last=t.scheduledDate;return h+taskHTML(t,{},'scheduled',t.scheduledDate)}).join('')}
function tasksForDate(date){const daily=tasks.filter(isDaily).sort(manualSort),scheduled=tasks.filter(t=>!isDaily(t)&&t.scheduledDate===date).sort((a,b)=>(a.scheduledTime||'99:99').localeCompare(b.scheduledTime||'99:99')||manualSort(a,b)),todayOnly=date===localISO()?tasks.filter(t=>!isDaily(t)&&!t.scheduledDate&&t.bucket==='today').sort(manualSort):[];return [...scheduled,...daily,...todayOnly]}
