const KEY='marlowe.tasks.v1',WORK_START=480,WORK_END=1020,DAY_CAPACITY=540;
const seedTasks=[{id:'seed-stpeters',title:"Contact St Peter's about book-hire covering",priority:1,minutes:25,due:'2026-08-18',bucket:'today',done:false,category:'Customer follow-up'},{id:'seed-peterpal',title:'Contact Peter Pal about the CoverPro',priority:2,minutes:20,due:'2026-08-18',bucket:'today',done:false,category:'CoverPro'},{id:'seed-schoolprep',title:'Prepare school visit materials + choose route',priority:2,minutes:25,due:'2026-08-18',bucket:'today',done:false,category:'School visits'},{id:'seed-schoolvisits',title:'School visits — aim for 4 local schools',priority:2,minutes:180,due:'2026-08-18',bucket:'today',done:false,category:'School visits'},{id:'seed-stripper',title:'CoverPro paper stripper — protected build block',priority:2,minutes:120,due:'2026-08-18',bucket:'today',done:false,category:'CoverPro'}];
let tasks=JSON.parse(localStorage.getItem(KEY)||'[]');if(!tasks.length){tasks=seedTasks.map(t=>({...t,created:new Date().toISOString()}));localStorage.setItem(KEY,JSON.stringify(tasks));}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function inferCategory(t){if(t.category)return t.category;const s=(t.title||'').toLowerCase();if(s.includes('school'))return'School visits';if(s.includes('coverpro')||s.includes('stripper'))return'CoverPro';if(s.includes('desk')||s.includes('admin'))return'Admin';if(s.includes('contact')||s.includes('follow'))return'Customer follow-up';return'General'}
tasks=tasks.map(t=>({...t,category:inferCategory(t),scheduledDate:t.scheduledDate||'',scheduledTime:t.scheduledTime||''}));
function localISO(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function dateFromISO(s){const[y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}function addDaysISO(s,n){const d=dateFromISO(s);d.setDate(d.getDate()+n);return localISO(d)}function nextBusinessDay(s){let d=addDaysISO(s,1);while([0,6].includes(dateFromISO(d).getDay()))d=addDaysISO(d,1);return d}
function businessLabel(s){return dateFromISO(s).toLocaleDateString(undefined,{weekday:'short',day:'numeric',month:'short'})}function timeLabel(s){if(!s)return'flexible';const[h,m]=s.split(':').map(Number),a=h>=12?'pm':'am',hh=((h+11)%12)+1;return `${hh}:${String(m).padStart(2,'0')} ${a}`}function fmtClock(total){const h=Math.floor(total/60)%24,m=total%60,a=h>=12?'pm':'am',hh=((h+11)%12)+1;return `${hh}:${String(m).padStart(2,'0')} ${a}`}
function startMinutes(t){if(!t.scheduledTime)return null;const[h,m]=t.scheduledTime.split(':').map(Number);return h*60+m}function endMinutes(t){const s=startMinutes(t);return s==null?null:s+Number(t.minutes||0)}
function minutesForDate(s,exclude=''){return tasks.filter(t=>!t.done&&t.scheduledDate===s&&t.id!==exclude).reduce((a,t)=>a+Number(t.minutes||0),0)}function findNextAvailable(start,mins,exclude=''){let d=start;for(let i=0;i<90;i++){if(![0,6].includes(dateFromISO(d).getDay())&&minutesForDate(d,exclude)+mins<=DAY_CAPACITY)return d;d=addDaysISO(d,1)}return''}
function save(){localStorage.setItem(KEY,JSON.stringify(tasks));render()}function score(t){let s=t.priority*100;if(t.due){const d=(new Date(t.due+'T23:59:59')-new Date())/86400000;s+=d<0?-400:Math.min(80,d*12)}if(t.bucket==='today')s-=120;return s}function niceDue(t){if(!t.due)return'';return `<span class="${t.due<localISO()&&!t.done?'overdue':''}">due ${esc(t.due)}</span>`}
function todayFinishMap(td){let cursor=Math.max(WORK_START,new Date().getHours()*60+new Date().getMinutes()),map={};td.forEach(t=>{if(t.done){map[t.id]=null;return}const fixed=startMinutes(t);if(fixed!=null){map[t.id]=fixed+Number(t.minutes||0);cursor=Math.max(cursor,map[t.id]);}else{cursor+=Number(t.minutes||0);map[t.id]=cursor}});return map}
function taskHTML(t,finishMap={}){const f=finishMap[t.id],late=Number.isFinite(f)&&f>WORK_END,finish=Number.isFinite(f)?`<span class="pill ${late?'late':'finish'}">finish ~${fmtClock(f)}</span>`:'',sched=t.scheduledDate?`<span class="pill scheduled">${businessLabel(t.scheduledDate)} · ${timeLabel(t.scheduledTime)}</span>`:'',res=late&&t.bucket==='today'&&!t.scheduledDate&&!t.done?`<button class="warnbtn" onclick="rescheduleTomorrow('${t.id}')">Reschedule for tomorrow</button>`:'';return `<div class="task ${t.done?'done':''}"><input type="checkbox" ${t.done?'checked':''} onchange="toggle('${t.id}')"><div><div class="task-title">${esc(t.title)}</div><div class="task-meta"><span class="pill cat">${esc(t.category)}</span><span class="pill">${t.minutes} min</span>${sched}${finish}<span class="pill">${['','Urgent','Important','Normal'][t.priority]}</span> ${niceDue(t)}</div>${res}</div><div><button class="ghost" onclick="move('${t.id}')">${t.scheduledDate?'Unschedule':(t.bucket==='today'?'Backlog':'Today')}</button><button class="ghost danger" onclick="del('${t.id}')">×</button></div></div>`}
function renderUpcoming(list){if(!list.length)return'<div class="empty">Nothing scheduled.</div>';let last='';return list.map(t=>{const h=t.scheduledDate!==last?`<div class="upcoming-day">${businessLabel(t.scheduledDate)}</div>`:'';last=t.scheduledDate;return h+taskHTML(t)}).join('')}